/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    H1: typeof import('./src/components/ui/H1.vue')['default']
    H2: typeof import('./src/components/ui/H2.vue')['default']
    H3: typeof import('./src/components/ui/H3.vue')['default']
    H4: typeof import('./src/components/ui/H4.vue')['default']
    IFluentAdd16Filled: typeof import('~icons/fluent/add16-filled')['default']
    IFluentBug16Regular: typeof import('~icons/fluent/bug16-regular')['default']
    IFluentCheckmark16Regular: typeof import('~icons/fluent/checkmark16-regular')['default']
    IFluentChevronDown16Regular: typeof import('~icons/fluent/chevron-down16-regular')['default']
    IFluentDocumentMultiple16Regular: typeof import('~icons/fluent/document-multiple16-regular')['default']
    IFluentQuestionCircle16Regular: typeof import('~icons/fluent/question-circle16-regular')['default']
    IFluentSettings16Regular: typeof import('~icons/fluent/settings16-regular')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    P: typeof import('./src/components/ui/P.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./src/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./src/components/ui/select/SelectLabel.vue')['default']
    SelectSeparator: typeof import('./src/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
