/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    IFluentAdd16Filled: typeof import('~icons/fluent/add16-filled')['default']
    IFluentBug16Regular: typeof import('~icons/fluent/bug16-regular')['default']
    IFluentDocumentMultiple16Regular: typeof import('~icons/fluent/document-multiple16-regular')['default']
    IFluentSettings16Regular: typeof import('~icons/fluent/settings16-regular')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    Navbar: typeof import('./src/components/nav/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
